version: 2
updates:
  # Update Pip Packages
  - package-ecosystem: "pip"
    directory: "/api/service/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # Update GH Actions  
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
