version: '3'

services:
  mysfitfrontend:
#    build: frontend/.
    image: nginx:alpine
    ports:
    - "8080:80"
    volumes:
    - "/c/projects/gobuild/frontend/static:/usr/share/nginx/html" # Customise Me

  mysfitapi:
    image: ollypom/mysfit:v3
    build:
      context: api/.
      dockerfile: Dockerfile.v3 
    ports:
    - "8081:8080"
    environment:
    - "AWS_ACCESS_KEY_ID=xyz"
    - "AWS_SECRET_ACCESS_KEY=xyz"
    - "MYSFIT_ENV=LOCAL"
    - "DDB_TABLE=mysfits"
    
  dynamodb:
    user: root
    image: amazon/dynamodb-local
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/
    volumes:
     - "dynamodb:/home/dynamodblocal/data"
    ports:
     - "9000:8000"

volumes:
  dynamodb: